version: "3.3"
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL-postgres://postgres:postgres@postgres:5432/postgres}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE-n4GVvZfpb4Tq2GEX1OhC2JgNGQ157G8PJs7SmJEVp8vVmtwgWZgxh1waNpva3YsD}
  postgres:
    image: postgres:16.3-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres-data:
